LOAD DATA INFILE '/var/lib/mysql-files/operadoras_financeiro.csv'
INTO TABLE operadoras_financeiro
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    REG_ANS = NULLIF(@REG_ANS, ''),
    CD_CONTA_CONTABIL = NULLIF(@CD_CONTA_CONTABIL, ''),
    DESCRICAO = NULLIF(@DESCRICAO, ''),
    VL_SALDO_INICIAL = NULLIF(@VL_SALDO_INICIAL, ''),
    VL_SALDO_FINAL = NULLIF(@VL_SALDO_FINAL, '');
